defaults:
  - model: resnet
  - dataset: 10_classes_supervised
  - optim: adamw
  - loss_fn: cross_entropy

epochs: 100

datamodule:
  _target_: data.datamodule.DataModule
  train_dataset_path: ${data_dir}/${dataset.train_path}
  val_dataset_path: ${data_dir}/${dataset.val_path}
  train_transform: ${dataset.train_transform}
  val_transform: ${dataset.test_transform}
  batch_size: 128
  num_workers: 8

data_dir: ${root_dir}/dataset
root_dir:  ${hydra:runtime.cwd}

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true